__title__ = 'ssaw'
__version__ = '0.0.6'
__description__ = 'Wrapper for Survey Solutions API'
__url__ = 'https://github.com/vavalomi/ssaw'
__author__ = 'Zurab Sajaia'
__author_email__ = 'vavalomi@hotmail.com'